name: Deploy to Firebase App Hosting

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20' # Or '22'
        cache-dependency-path: webapp/package-lock.json

    - name: Cache Node Modules
      uses: actions/cache@v4
      with:
        path: webapp/node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('webapp/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install Webapp Dependencies
      run: cd webapp && npm install

    - name: Build Web Application
      run: cd webapp && npm run build

    - name: Install Firebase CLI
      run: npm install -g firebase-tools

    - name: Authenticate to Google Cloud
      id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        workload_identity_provider: 'projects/641713712205/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-provider'
        service_account: 'github-action-1042088109@pim-and-order-management.iam.gserviceaccount.com'

    - name: Deploy to Firebase App Hosting
      # ADD THE --project FLAG HERE!
      run: firebase deploy --only apphosting --project pim-and-order-management # <<< ADDED --project
      env:
        FIREBASE_PROJECT: pim-and-order-management # This env var is good, but the --project flag is more direct for deploy command
